export const GET_COMMENTS = "GET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const COMMENT_ADDED = "COMMENT_ADDED";
export const CHANGE_COMMENT_TITLE = "CHANGE_COMMENT_TITLE";
export const CHANGE_COMMENT_CONTENT = "CHANGE_COMMENT_CONTENT";